### ISSUE TITLE
增加生成单接口测试用例的功能

### ISSUE THREAD

**Issue by grassroadsZ** [tahitimoon/LunarLink#11]
1.一个全新的平台,无论是使用swagger 接口导入还是使用yapi 导入, 导入的都只是接口, 由单接口而需要产生的测试用例并没有, 光导入了接口, 然后单接口的测试用例还是要自己一个个的拖拉拽去生成, 这一步的操作反而更浪费时间

2.另外默认的状态码校验这个是否支持全局配置 配置,举例,系统只要接口通了 http码就是200 ,但是实际可能是根据响应的data 里面的code 去判断是否业务有异常

1里面的步骤暂时可能需要使用已有的系统添加的接口去写代码 先生成一波
2. 这个可能是要对导入yapi 时进行修改源代码进行校验的修改

**Comment by tahitimoon** [comment]
> 1.一个全新的平台,无论是使用swagger 接口导入还是使用yapi 导入, 导入的都只是接口, 由单接口而需要产生的测试用例并没有, 光导入了接口, 然后单接口的测试用例还是要自己一个个的拖拉拽去生成, 这一步的操作反而更浪费时间
> 
> 2.另外默认的状态码校验这个是否支持全局配置 配置,举例,系统只要接口通了 http码就是200 ,但是实际可能是根据响应的data 里面的code 去判断是否业务有异常
> 
> 1里面的步骤暂时可能需要使用已有的系统添加的接口去写代码 先生成一波 2. 这个可能是要对导入yapi 时进行修改源代码进行校验的修改

1. 可以试试录制流量生成用例，作为一个全新的平台确实有一个接口量的积累过程，具体实现什么场景的用例还需要自己去组合。
2. 全局断言这个想法不错，后续可以考虑增加。
