### ISSUE TITLE
通过docker部署，lunar-link-proxy容器状态一直显示 restarting

### ISSUE THREAD

**Issue by lamboxr** [tahitimoon/LunarLink#12]
lunar-link-proxy                    "python proxy.py"        10 minutes ago   Restarting (0) 37 seconds ago

**Comment by tahitimoon** [comment]
> lunar-link-proxy "python proxy.py" 10 minutes ago Restarting (0) 37 seconds ago

试试`docker logs lunar-link-proxy`命令，看看什么错误造成的。是使用的`docker-compose.yml`部署的吗？是不是mysql、redis连接都正常吧
