### ISSUE TITLE
为啥我搭建的跟示例不一样

### ISSUE THREAD

**Issue by ganchaoren** [tahitimoon/LunarLink#13]
![image](https://github.com/tahitimoon/LunarLink/assets/171331370/b914c23b-40d0-4bdc-a3e5-b456d3af9712)

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/171331370/335517450-b914c23b-40d0-4bdc-a3e5-b456d3af9712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDkwODUsIm5iZiI6MTcxNzE0ODc4NSwicGF0aCI6Ii8xNzEzMzEzNzAvMzM1NTE3NDUwLWI5MTRjMjNiLTQwZDAtNGJkYy1hM2U1LWI0NTZkM2FmOTcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwOTQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWEyZGE4ZGVmMjQ2OWM2NjY3ZjQxMDVhNjVlZTBmOGZhNTUwOGEzOTAwN2U4YWRlZWIwYTczY2E0YzBlM2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mg_fCUMnCjtOlV6s4RxNPmzqT2Jcrld0ghvs6b9Ff7M)

这个是后台管理账号的地方，要访问测试平台的话，http://127.0.0.1:8888
详细的操作参照操作手册：https://lunar-link-docs.fun/
