### ISSUE TITLE
我这个账号绑定了一个有所有权限的分组，为啥登录后侧边菜单还是无法点击呐，数据库也对上了

### ISSUE THREAD

**Issue by ganchaoren** [tahitimoon/LunarLink#14]
![image](https://github.com/tahitimoon/LunarLink/assets/171331370/6ee34459-bdfb-4515-815a-fdccb74d1934)
![image](https://github.com/tahitimoon/LunarLink/assets/171331370/27eb418c-a8d1-4c49-a7b7-55780660d4d8)
![image](https://github.com/tahitimoon/LunarLink/assets/171331370/c7e920b5-717a-436f-ba84-b5feadb43162)
![image](https://github.com/tahitimoon/LunarLink/assets/171331370/3287fbf3-8108-4eef-9b19-9295b470c21c)

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/171331370/335539409-6ee34459-bdfb-4515-815a-fdccb74d1934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTEwNjMsIm5iZiI6MTcxNzE1MDc2MywicGF0aCI6Ii8xNzEzMzEzNzAvMzM1NTM5NDA5LTZlZTM0NDU5LWJkZmItNDUxNS04MTVhLWZkY2NiNzRkMTkzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTZlOTJkZGNjMTM5NzIwZmI4ZGNkZTg4YjBmNTYyMjA5OWUwMTc0ZDVjZmNhMWI5MWEyNzYyMDhlYjJhZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XI27RGwbN1blLXK6CxsSB2mjMLiNScx6tAV9fD0ztFI) ![image](https://private-user-images.githubusercontent.com/171331370/335539743-27eb418c-a8d1-4c49-a7b7-55780660d4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTEwNjMsIm5iZiI6MTcxNzE1MDc2MywicGF0aCI6Ii8xNzEzMzEzNzAvMzM1NTM5NzQzLTI3ZWI0MThjLWE4ZDEtNGM0OS1hN2I3LTU1NzgwNjYwZDRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGFiNzgzNmQyNTYyZGM4M2UxMjQ2ZGU1ZTM0YWExNmVmZjY4MjQ3NTljZTcwYmQ1Y2I0MGI2Y2RkNGE1MGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JgclBxX1MujQ5QA7OtxsVgIkSQIa3cr0lSomg2G5Xr4) ![image](https://private-user-images.githubusercontent.com/171331370/335539901-c7e920b5-717a-436f-ba84-b5feadb43162.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTEwNjMsIm5iZiI6MTcxNzE1MDc2MywicGF0aCI6Ii8xNzEzMzEzNzAvMzM1NTM5OTAxLWM3ZTkyMGI1LTcxN2EtNDM2Zi1iYTg0LWI1ZmVhZGI0MzE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWZhMTA4ZjJjNWFhMzExZGFkMjg1NGI1MTNlODAxYjNjNjU0MmViMmJkZGE2NDc0MTJiNGZiNzBkYzJhYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0q0lSD5J3dy7AWlZB8IgQUfj1Dy8aeYigSCAE_UmF6s) ![image](https://private-user-images.githubusercontent.com/171331370/335540851-3287fbf3-8108-4eef-9b19-9295b470c21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTEwNjMsIm5iZiI6MTcxNzE1MDc2MywicGF0aCI6Ii8xNzEzMzEzNzAvMzM1NTQwODUxLTMyODdmYmYzLTgxMDgtNGVlZi05YjE5LTkyOTViNDcwYzIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWM4MjZjZTY1MjI4ZTgzNWI0NjA2ZDY0N2VmZmFjYzFmYmZhM2Q2YzU4NWI3MmM1OGQ5MTk0NGE5MjIxZGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lopKydMmgubmWrxMhDjlkE0E2D2hlg0ibcRrLEG-n4E)

点击编辑按钮旁边的“进入”按钮就能看到了
<img width="1467" alt="image" src="https://github.com/tahitimoon/LunarLink/assets/37645552/fbdba02b-df91-4733-8d2c-9ad7f4c73a05">

**Comment by tahitimoon** [comment]
> 好吧 我这笔记本屏幕太窄了，按钮没渲染出来

现在小尺寸的屏幕没做兼容，正常24寸显示都可以的
