### ISSUE TITLE
登录日志无法显示

### ISSUE THREAD

**Issue by Solomon-hjf** [tahitimoon/LunarLink#15]
作者你好，请问登录日志我打开后是空白的，数据库也没有记录，请问这个是在哪里被调用的啊？

**Comment by tahitimoon** [comment]
使用docker一键部署还是本地安装部署？推荐python版本和其他中间件版本全部要对应上。

**Comment by Solomon-hjf** [comment]
我使用的是本地安装部署

**Comment by tahitimoon** [comment]
> 我使用的是本地安装部署

可能是本地组件有问题，mysql redis这些版本最好也对应上
