### ISSUE TITLE
小白求教下，源码这里模块导入为什么会报错？

### ISSUE THREAD

**Issue by daai** [tahitimoon/LunarLink#18]
![image](https://github.com/tahitimoon/LunarLink/assets/13166319/b44bab23-13c3-4690-b1cb-1d7e2705fa3f)

改成apps.lunarlink.utils.parser import Format 是没问题的。

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/13166319/344081725-b44bab23-13c3-4690-b1cb-1d7e2705fa3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODA3MTgsIm5iZiI6MTcxOTU4MDQxOCwicGF0aCI6Ii8xMzE2NjMxOS8zNDQwODE3MjUtYjQ0YmFiMjMtMTNjMy00NjkwLWIxY2ItMWQ3ZTI3MDVmYTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEzMTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMTRlMjYyMWFiYTEyNzlkNWFhZjZjZTE1OTRkNWFmODczZGFkN2Q2MTFkODYzMTY5MjY2MWYxZjRlYjc2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vdX4RwTJ5bo2RaKHsXHLHSrKcm5FINh_dHW4nlKHQiU)
> 
> 改成apps.lunarlink.utils.parser import Format 是没问题的。

<img width="493" alt="image" src="https://github.com/tahitimoon/LunarLink/assets/37645552/51c0fd83-6d6e-40c7-9857-95949128679f">
如上图，将`apps`和`extra_apps`设置为源代码根目录
