### ISSUE TITLE
驱动代码中的带参数的方法在用例中无法使用？

### ISSUE THREAD

**Issue by heuje** [tahitimoon/LunarLink#19]
def fun(name):
    return {"age": "18岁"}

要取到带参数的函数的返回值
${fun("zhangsan")}  # 这样写不生效

要取到年龄
${fun("zhangsan")["age"]}
${fun("zhangsan")}["age"]

**Comment by tahitimoon** [comment]
> def fun(name): return {"age": "18岁"}
> 
> 要取到带参数的函数的返回值 ${fun("zhangsan")} # 这样写不生效
> 
> 要取到年龄 ${fun("zhangsan")["age"]} ${fun("zhangsan")}["age"]

如果像`${fun("zhangsan")}`这样的话，${fun(zhangsan)}内容不加引号就好了

**Comment by heuje** [comment]
variable_regexp = r"\$([\w_]+)"
function_regexp = r"\$\{([\w_]+\([\$\w\.\-/_ =,]*\))\}"
function_regexp_compile = re.compile(r"^([\w_]+)\(([\$\w\.\-/_ =,]*)\)$")

# use $$ to escape $ notation
dolloar_regex_compile = re.compile(r"\$\$")
# variable notation, e.g. ${var} or $var
variable_regex_compile = re.compile(r"\$\{(\w+)\}|\$(\w+)")
# function notation, e.g. ${func1($var_1, $var_3)}
function_regex_compile = re.compile(r"\$\{(\w+)\(([\$\w\.\-/\s=,]*)\)\}")
-----------------------------------------------------------------------------------------

看到源码这里了，试了下貌似要不支持参数传中文？

**Comment by tahitimoon** [comment]
> variable_regexp = r"$([\w_]+)" function_regexp = r"${([\w_]+([$\w.-/_ =,]_))}" function_regexp_compile = re.compile(r"^([\w_]+)(([$\w.-/_ =,]_))$")
> 
> # use $$ to escape $ notation
> dolloar_regex_compile = re.compile(r"$$")
> 
> # variable notation, e.g. ${var} or $var
> variable_regex_compile = re.compile(r"${(\w+)}|$(\w+)")
> 
> # function notation, e.g. ${func1($var_1, $var_3)}
> ## function_regex_compile = re.compile(r"${(\w+)(([$\w.-/\s=,]*))}")
> 看到源码这里了，试了下貌似要不支持参数传中文？

以正常的编程习惯，还是不要传中文了
