### ISSUE TITLE
后台管理，用户和权限相关，未配置驱动库权限的用户，仍可以修改驱动库的代码？是否给了项目的查看权限，就可以修改项目下驱动库的代码？

### ISSUE THREAD

**Issue by heuje** [tahitimoon/LunarLink#20]
![image](https://github.com/user-attachments/assets/5ac8cbf6-8797-400f-a83b-e35f085586a8)

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/23732494/350342313-5ac8cbf6-8797-400f-a83b-e35f085586a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTc1MjMsIm5iZiI6MTcyMTQ1NzIyMywicGF0aCI6Ii8yMzczMjQ5NC8zNTAzNDIzMTMtNWFjOGNiZjYtODc5Ny00MDBmLWE4M2ItZTM1ZjA4NTU4NmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA2MzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDlkZGQ4YzYyZjU5NzYzN2U5MzNkNzYxOWIzNzFmZTkyM2VhYTNiYjBhODA4MzY0NDZmOThhY2EzOWM2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nd8ZDNr4oHXaA7pfBabo70rfjjpOVCD8WnJVxjocJnI)

默认用户都有权限修改前端页面的驱动代码，这个在视图层没做权限管理，这个管理后台只是django，和drf没关系

**Comment by heuje** [comment]
那如果要权限能控制到普通用户不能编辑驱动代码，需要修改哪里？

**Comment by tahitimoon** [comment]
> 那如果要权限能控制到普通用户不能编辑驱动代码，需要修改哪里？

直接在保存驱动代码的接口视图层控制下权限就好啦，如果前端需要根据普通用户不能编辑，只有超级管理员能编辑，参照删除项目权限，禁用前端组件编辑功能

**Comment by heuje** [comment]
明白了，感谢，已修改
