### ISSUE TITLE
用例里步骤A定义的变量，如何在步骤B也可以使用呢？

### ISSUE THREAD

**Issue by heuje** [tahitimoon/LunarLink#21]
用例内变量如何共享使用？

**Comment by tahitimoon** [comment]
> 用例内变量如何共享使用？

能再说的详细一点么？

**Comment by heuje** [comment]
![image](https://github.com/user-attachments/assets/a44b4e80-2e3e-4d65-8f94-1129f01d9c61)

**Comment by heuje** [comment]
![image](https://github.com/user-attachments/assets/4a7709e5-4b1a-48f1-9e11-64d7dac86d8e)

**Comment by heuje** [comment]
如图，用例中有两个步骤（接口）

**Comment by tahitimoon** [comment]
> 如图，用例中有两个步骤（接口）

这边测试了一下，是可以引用的，你看看是不是你引用的变量类型不对
<img width="721" alt="image" src="https://github.com/user-attachments/assets/0afc6bee-44e8-4884-872e-d53c457ce3e3">
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/b62eace7-eb8a-463a-a5c2-6ba36fe88045">
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/a5e664a0-cf2b-4660-b6f3-45438f833de9">
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/d3c4ad1c-5067-4c78-9412-0f35bbc67dd2">

**Comment by heuje** [comment]
我这边第二个接口报错找不到变量
![Uploading image.png…]()

**Comment by heuje** [comment]
![image](https://github.com/user-attachments/assets/2d72ece7-610e-443d-ac87-bbe42f520425)

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/23732494/350838360-2d72ece7-610e-443d-ac87-bbe42f520425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjY3MjcsIm5iZiI6MTcyMTYyNjQyNywicGF0aCI6Ii8yMzczMjQ5NC8zNTA4MzgzNjAtMmQ3MmVjZTctNjEwZS00NDNkLWFjODctYmJlNDJmNTIwNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA1MzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDc0ZWJlNWQ5M2UyMjg2OGNkYWQ1MGYyNWQ5OGFmYTE4ZWVjNTk1OTU4ZmM1ZjYyYmFhY2NiZWIyZWY4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbYIpdGayQ2WqxAwRSi7mUICwAeZL56bzY38dxaHNfE)

应该是引用不到，如果这种变量在上个接口中也是通过驱动代码的函数引用的，直接在这个接口里面也可以直接引用这个函数啦

**Comment by heuje** [comment]
在上个接口中也是通过驱动代码的函数引用的，确实是可以直接在这个接口里面引用这个函数，但是有的场景接口间有关联性，第二步需要引用变量的值和第一次一致，代码里需要动哪块的东西？变量可以调整成用例级别吗？

**Comment by tahitimoon** [comment]
> 在上个接口中也是通过驱动代码的函数引用的，确实是可以直接在这个接口里面引用这个函数，但是有的场景接口间有关联性，第二步需要引用变量的值和第一次一致，代码里需要动哪块的东西？变量可以调整成用例级别吗？

大部分情况下都是引用上一个接口返回的字段吧，具体改动哪一块可以研究下。不过觉得没必要呀
