### ISSUE TITLE
求助：定时任务触发失败

### ISSUE THREAD

**Issue by Solomon-hjf** [tahitimoon/LunarLink#23]
楼主你好，我安装你的教程在docker上部署后，正常启动。但是定时任务模块没有触发，只能手动触发，并且也没有钉钉的推送。能分析下是什么原因吗？感谢

**Comment by tahitimoon** [comment]
> 楼主你好，我安装你的教程在docker上部署后，正常启动。但是定时任务模块没有触发，只能手动触发，并且也没有钉钉的推送。能分析下是什么原因吗？感谢

- 去定时任务的 docker 容器看看日志什么情况，是消息队列没连上还是啥，命令`sudo docker logs -f 容器_id`
- 默认不支持钉钉，只支持企业微信机器人，可以参照企微机器人的方式实现，很简单

**Comment by Solomon-hjf** [comment]
好的，谢谢答复。钉钉发送应该也是在E:\git\LunarLink-1.0.6\backend\apps\lunarlink\utils\qy_message.py 这个文件里改吧？

**Comment by tahitimoon** [comment]
> 好的，谢谢答复。钉钉发送应该也是在E:\git\LunarLink-1.0.6\backend\apps\lunarlink\utils\qy_message.py 这个文件里改吧？

可以额外新建一个py文件，方便管理
