### ISSUE TITLE
全局变量功能咨询

### ISSUE THREAD

**Issue by Solomon-hjf** [tahitimoon/LunarLink#24]
你好，我有一个测试场景请问平台能否支持这个功能：
1、登录获取token后，是否能保存到全局变量中让其他接口使用

在考虑到多条测试用例可能都要在同一被测系统进行执行，希望登录只执行一次，以免被测系统检测多次登录造成防御措施。

**Comment by tahitimoon** [comment]
- 支持，登录接口放最前面就好了，然后把token提取出来保存，后面这些接口都引用这个token就好了。
- 但是现在是一个测试用例需要登录一次，然后后面所有的执行步骤再引用这个token。
- 还有一个方式，就是把token提前用一个全局变量保存起来，然后引用就好了。
详细使用方法请参照文档：https://lunar-link-docs.fun/docs/guide/introduce.html

**Comment by Solomon-hjf** [comment]
谢谢你的回复。

如果我想所有的测试用例用一个token，且只登录一次呢？我打算把一组用例组成一个套件，批量执行。

比如说
我第一条用例执行了登录，把token保存在全局变量里。

第二个用例可以直接使用吗？


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月23日 15:57 |
| 收件人 | tahitimoon/LunarLink ***@***.***> |
| 抄送人 | HJF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) |

支持，登录接口放最前面就好了，然后把token提取出来保存，后面这些接口都引用这个token就好了。
但是现在是一个测试用例需要登录一次，然后后面所有的执行步骤再引用这个token。
还有一个方式，就是把token提前用一个全局变量保存起来，然后引用就好了。
详细使用方法请参照文档：https://lunar-link-docs.fun/docs/guide/introduce.html

**Comment by tahitimoon** [comment]
> 谢谢你的回复。 如果我想所有的测试用例用一个token，且只登录一次呢？我打算把一组用例组成一个套件，批量执行。 比如说 我第一条用例执行了登录，把token保存在全局变量里。 第二个用例可以直接使用吗？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年08月23日 15:57 | | 收件人 | tahitimoon/LunarLink ***@***.***> | | 抄送人 | HJF ***@***.***>, Author ***@***.***> | | 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) | 支持，登录接口放最前面就好了，然后把token提取出来保存，后面这些接口都引用这个token就好了。 但是现在是一个测试用例需要登录一次，然后后面所有的执行步骤再引用这个token。 还有一个方式，就是把token提前用一个全局变量保存起来，然后引用就好了。 详细使用方法请参照文档：https://lunar-link-docs.fun/docs/guide/introduce.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

测试用例不能作为套件被另外一个用例使用，如果你只是想使用一个token所有用例都能用的话，直接在`全局变量`中定义一个变量保存token值，然后在所用用例中引用就好啦

**Comment by Solomon-hjf** [comment]
好滴好滴，谢谢。我刚才还在尝试，能不能把测试用例中第一条登录接口的返回值，保存到全局变量里。好像不太行。我再尝尝一下其他方案吧，感谢！


| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月26日 13:55 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) |

谢谢你的回复。 如果我想所有的测试用例用一个token，且只登录一次呢？我打算把一组用例组成一个套件，批量执行。 比如说 我第一条用例执行了登录，把token保存在全局变量里。 第二个用例可以直接使用吗？
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年08月23日 15:57 | | 收件人 | tahitimoon/LunarLink @.> | | 抄送人 | HJF @.>, Author @.> | | 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) | 支持，登录接口放最前面就好了，然后把token提取出来保存，后面这些接口都引用这个token就好了。 但是现在是一个测试用例需要登录一次，然后后面所有的执行步骤再引用这个token。 还有一个方式，就是把token提前用一个全局变量保存起来，然后引用就好了。 详细使用方法请参照文档：https://lunar-link-docs.fun/docs/guide/introduce.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

测试用例不能作为套件被另外一个用例使用，如果你只是想使用一个token所有用例都能用的话，直接在全局变量中定义一个变量保存token值，然后在所用用例中引用就好啦

**Comment by tahitimoon** [comment]
> 好滴好滴，谢谢。我刚才还在尝试，能不能把测试用例中第一条登录接口的返回值，保存到全局变量里。好像不太行。我再尝尝一下其他方案吧，感谢！ | | hujf1203 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年8月26日 13:55 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) | 谢谢你的回复。 如果我想所有的测试用例用一个token，且只登录一次呢？我打算把一组用例组成一个套件，批量执行。 比如说 我第一条用例执行了登录，把token保存在全局变量里。 第二个用例可以直接使用吗？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年08月23日 15:57 | | 收件人 | tahitimoon/LunarLink @.> | | 抄送人 | HJF @.>, Author @.> | | 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) | 支持，登录接口放最前面就好了，然后把token提取出来保存，后面这些接口都引用这个token就好了。 但是现在是一个测试用例需要登录一次，然后后面所有的执行步骤再引用这个token。 还有一个方式，就是把token提前用一个全局变量保存起来，然后引用就好了。 详细使用方法请参照文档：https://lunar-link-docs.fun/docs/guide/introduce.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 测试用例不能作为套件被另外一个用例使用，如果你只是想使用一个token所有用例都能用的话，直接在全局变量中定义一个变量保存token值，然后在所用用例中引用就好啦 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

- 只能在每条用例都放一个登录接口了，然后将token提取出来保存为变量，不过这个变量作用域仅限于用例，如果你这个token有效期比较长也可以在全局变量里面写死。
- 还有种方式，全局变量其实可以调用驱动代码里面的函数，看能不能看登录接口以代码的形式写在驱动代码里面，然后全局变量再调用这个函数获取token。

**Comment by Solomon-hjf** [comment]
目前来看，写死应该是能实现的方案了。
我刚才调试代码，发现如果在驱动代码里写登录函数，不管在接口里有没有调用，都会执行一次。


博主能不能留个联系方式，方便以后能深入交流一下。


| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月26日 14:10 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) |

好滴好滴，谢谢。我刚才还在尝试，能不能把测试用例中第一条登录接口的返回值，保存到全局变量里。好像不太行。我再尝尝一下其他方案吧，感谢！ | | hujf1203 | | @.*** | ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年8月26日 13:55 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) | 谢谢你的回复。 如果我想所有的测试用例用一个token，且只登录一次呢？我打算把一组用例组成一个套件，批量执行。 比如说 我第一条用例执行了登录，把token保存在全局变量里。 第二个用例可以直接使用吗？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年08月23日 15:57 | | 收件人 | tahitimoon/LunarLink @.> | | 抄送人 | HJF @.>, Author @.> | | 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) | 支持，登录接口放最前面就好了，然后把token提取出来保存，后面这些接口都引用这个token就好了。 但是现在是一个测试用例需要登录一次，然后后面所有的执行步骤再引用这个token。 还有一个方式，就是把token提前用一个全局变量保存起来，然后引用就好了。 详细使用方法请参照文档：https://lunar-link-docs.fun/docs/guide/introduce.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 测试用例不能作为套件被另外一个用例使用，如果你只是想使用一个token所有用例都能用的话，直接在全局变量中定义一个变量保存token值，然后在所用用例中引用就好啦 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

只能在每条用例都放一个登录接口了，然后将token提取出来保存为变量，不过这个变量作用域仅限于用例，如果你这个token有效期比较长也可以在全局变量里面写死。
还有种方式，全局变量其实可以调用驱动代码里面的函数，看能不能看登录接口以代码的形式写在驱动代码里面，然后全局变量再调用这个函数获取token。

**Comment by tahitimoon** [comment]
> 博主能不能留个联系方式，方便以后

有啥问题直接在这里提issue就好啦。看到我都会回的

**Comment by Solomon-hjf** [comment]
好滴好滴，谢谢了


| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月26日 14:19 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 全局变量功能咨询 (Issue #24) |

博主能不能留个联系方式，方便以后

有啥问题直接在这里提issue就好啦。看到我都会回的

**Comment by easy-come2024** [comment]
全局变量token值刷新一次多次引用方法
![企业微信截图_17338826736574](https://github.com/user-attachments/assets/cc6119b8-8871-45e7-93b5-5997dec75ca0)
