### ISSUE TITLE
无法找到名为 log_request_id.filters 的模块

### ISSUE THREAD

**Issue by elaine-mulinsen** [tahitimoon/LunarLink#25]
hello,感谢分享,看到LunarLink，想尝试下。遇到错误了，可以帮忙看下嘛？
Python 无法找到名为 log_request_id.filters 的模块,是什么原因哈？

<img width="365" alt="1" src="https://github.com/user-attachments/assets/c9d59825-7e70-40c5-93de-02f7f91b5dd5">
<img width="462" alt="2" src="https://github.com/user-attachments/assets/de11b733-959e-4772-8053-eef61a591c62">

**Comment by tahitimoon** [comment]
> log_request_id

你是用哪种方式部署安装的了？看提示是少了库，pip install 单独安装就好啦

**Comment by hdd-tongchenghedandan** [comment]
用pip安装过了这个库log_request_id，还是这样提示

**Comment by tahitimoon** [comment]
> 用pip安装过了这个库log_request_id，还是这样提示

还是需要按照操作文档来部署，所有组件的版本以及Python的版本都要对应上
