### ISSUE TITLE
pip安装了这个库log_request_id，就是这样的提示，咋办> log_request_id

### ISSUE THREAD

**Issue by elaine-mulinsen** [tahitimoon/LunarLink#27]
> log_request_id

你是用哪种方式部署安装的了？看提示是少了库，pip install 单独安装就好啦

_Originally posted by @tahitimoon in https://github.com/tahitimoon/LunarLink/issues/25#issuecomment-2374153176_

**Comment by tahitimoon** [comment]
重复问题
