### ISSUE TITLE
关于录制用例的问题

### ISSUE THREAD

**Issue by Solomon-hjf** [tahitimoon/LunarLink#28]
博主你好：
       在录制用例模块，我有一个概念不理解。在说明文档中，第一步是设置代理。
       这里的代理设置是在操作平台的客户端进行设置，还是在部署服务的服务端进行设置？
       因为我目前项目在linux服务器上用docker部署的。访问平台是在Windows客户端访问执行的。
    
希望博主予以解答，谢谢。

**Comment by tahitimoon** [comment]
> 博主你好： 在录制用例模块，我有一个概念不理解。在说明文档中，第一步是设置代理。 这里的代理设置是在操作平台的客户端进行设置，还是在部署服务的服务端进行设置？ 因为我目前项目在linux服务器上用docker部署的。访问平台是在Windows客户端访问执行的。
> 
> 希望博主予以解答，谢谢。

第一步设置代理是在操作平台的客户端进行设置（把部署服务器的ip:端口设置为代理），然后在测试平台上面开启录制就好了，操作文档和说明原理在这https://lunar-link-docs.fun/docs/guide/test_case.html#%E9%80%89%E6%8B%A9%E6%8E%A5%E5%8F%A3%E7%BB%84%E5%90%88%E6%88%90%E7%94%A8%E4%BE%8B

**Comment by Solomon-hjf** [comment]
我按照您的操作文档设置好代理后，录制完成后，点击获取录制接口，没有任何内容出现，可能是什么原因呢？






| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月1日 10:48 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 关于录制用例的问题 (Issue #28) |

博主你好： 在录制用例模块，我有一个概念不理解。在说明文档中，第一步是设置代理。 这里的代理设置是在操作平台的客户端进行设置，还是在部署服务的服务端进行设置？ 因为我目前项目在linux服务器上用docker部署的。访问平台是在Windows客户端访问执行的。

希望博主予以解答，谢谢。

第一步设置代理是在操作平台的客户端进行设置（把部署服务器的ip:端口设置为代理），然后在测试平台上面开启录制就好了，操作文档和说明原理在这https://lunar-link-docs.fun/docs/guide/test_case.html#%E9%80%89%E6%8B%A9%E6%8E%A5%E5%8F%A3%E7%BB%84%E5%90%88%E6%88%90%E7%94%A8%E4%BE%8B

**Comment by tahitimoon** [comment]
是部署在本地服务器还是云服务器了？

**Comment by Solomon-hjf** [comment]
第一次尝试：


服务部署在本地内网服务器（10.x.x.x）。
然后我在客户端，插网线访问平台。
我在客户端设置了代理服务器10.x.x.x:7778
并在本地客户端安装证书。
访问平台后，点击开始录制不报错，然后录制完成后点击停止录制。
点击获取录制接口，没有反应，没有内容出现。






=================================================================
第二次尝试（DEBUG）：
我在本地开发端，连接内网服务器上的数据库，本地（127.0.0.1）的redis。
我在客户端设置了代理服务器10.x.x.x:7778 


录制接口的过程中，还是没有数据，并且在redis没有看到缓存的result.
 


排查了半天，没有找到原因。。。 








| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月5日 17:14 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 关于录制用例的问题 (Issue #28) |

是部署在本地服务器还是云服务器了？

**Comment by tahitimoon** [comment]
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/3ea37341-41f4-4de4-9394-c4d63b6abde5">
先到这里测试一下能不能录制本机，再看看录制的节点启动成功没有

**Comment by Solomon-hjf** [comment]
请问怎么看录制的节点是否启动呢？
我之前录制的时候，就是点击的录制本机。






| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月5日 17:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 关于录制用例的问题 (Issue #28) |
image.png (view on web) 先到这里测试一下能不能录制本机，再看看录制的节点启动成功没有

**Comment by Solomon-hjf** [comment]
上面三个接口分别是：
开始录制
停止录制
获取录制接口 


后台的输出也没有报错
 











| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月5日 17:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 关于录制用例的问题 (Issue #28) |
image.png (view on web) 先到这里测试一下能不能录制本机，再看看录制的节点启动成功没有

**Comment by tahitimoon** [comment]
看不到你发的图片，录制本机的时候，需要填写录制的网站，如果录制成功，本机的ip会写入redis

**Comment by Solomon-hjf** [comment]
在录制的过程中，redis中有以下的数据：
Key:      fastapi:record:ip:127.0.0.1  
Value:   {

"user_id": 2,

"regex": "www.baidu.com",

"ip": "127.0.0.1",

"local": true

}







Key: fastapi:user:id:2

Value: {

"user_id": 2,

"regex": "www.baidu.com",

"ip": "127.0.0.1",

"local": true

}




再没有别的东西了，期间内容也没有增长。

然后我停止录制后，上述内容被清空。获取录制接口也是空的。







能不能帮忙定位一下，录制的接口是放在那里了呢？





| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月6日 13:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 关于录制用例的问题 (Issue #28) |

看不到你发的图片，录制本机的时候，需要填写录制的网站，如果录制成功，本机的ip会写入redis

**Comment by Solomon-hjf** [comment]
对了，博主。
点击录制后，目标网址是会自己弹出来，还是需要手动在浏览器输入网址，再进行操作？
目前的情况是，没有弹出来网页






| |
hujf1203
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月6日 13:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [tahitimoon/LunarLink] 关于录制用例的问题 (Issue #28) |

看不到你发的图片，录制本机的时候，需要填写录制的网站，如果录制成功，本机的ip会写入redis

**Comment by tahitimoon** [comment]
需要自己打开浏览器操作
