### ISSUE TITLE
购买资源

### ISSUE THREAD

**Issue by zhatianbang** [tahitimoon/LunarLink#29]
你好，有视频教程么，可以付费购买，我微信dkj214218

**Comment by tahitimoon** [comment]
> 你好，有视频教程么，可以付费购买，我微信dkj214218

已经写的很详细啦，还需要什么视频嘛。

**Comment by zhatianbang** [comment]
需要教程或者教学视频的，不然看不懂，本人菜呀，大佬能否提供呀
