### ISSUE TITLE
列表不展示内容，添加了接口，目录只有数量

### ISSUE THREAD

**Issue by songliqiang520** [tahitimoon/LunarLink#3]
![image](https://github.com/tahitimoon/LunarLink/assets/34465699/e5c14420-881f-4f35-824d-e6d425eedd77)
列表不展示内容，添加了接口，目录只有数量

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/34465699/316475118-e5c14420-881f-4f35-824d-e6d425eedd77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjg5MjEsIm5iZiI6MTcxMTM2ODYyMSwicGF0aCI6Ii8zNDQ2NTY5OS8zMTY0NzUxMTgtZTVjMTQ0MjAtODgxZi00ZjM1LTgyNGQtZTZkNDI1ZWVkZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEyMTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYmIwZjNlYzE5YjBjYzg5NzJiMGRiNTc3NmVmNTY4OGIxZTFjYzVjYmFhNDUwMjNiOTMxOWZmODgzN2RhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oh7Pih9W485Bl84cU-DnXDZ2UtmZrU1CWkq4nVfsCsY) 列表不展示内容，添加了接口，目录只有数量

如果是在本地部署需要登录管理后台，完善姓名，看你上面筛选那里显示null，应该是没完善姓名，参照文档https://lunarlink-doc.vercel.app/docs/guide/user_manage.html#%E6%96%B0%E5%A2%9E%E7%94%A8%E6%88%B7

**Comment by songliqiang520** [comment]
大佬，链接打不开

**Comment by tahitimoon** [comment]
> 大佬，链接打不开

http://127.0.0.1:8000/admin/  登录管理后台设置admin账号的姓名就好啦
