### ISSUE TITLE
有问题指教

### ISSUE THREAD

**Issue by a851379672** [tahitimoon/LunarLink#30]
有些问题指教，作者可否留个联系方式，或者加一下我vx：851379672

**Comment by tahitimoon** [comment]
有问题直接在这里提就好啦

**Comment by a851379672** [comment]
> 有问题直接在这里提就好啦

好的，主要是github经常连不上所以想要有个国内的沟通渠道
请问驱动代码那里能否读取到项目里的其他文件？我是想要读取其他代码文件，以及做一些接口文件上传的处理

**Comment by a851379672** [comment]
> 有问题直接在这里提就好啦

还会有一个问题是：不同环境的登陆是怎么做的请求头Authorization环境配置
环境配置的流程是在用例接口运行的前置，我该如何调用登陆接口后，赋值token给环境配置里的请求头做环境变量呢？

**Comment by tahitimoon** [comment]
> > 有问题直接在这里提就好啦
> 
> 好的，主要是github经常连不上所以想要有个国内的沟通渠道 请问驱动代码那里能否读取到项目里的其他文件？我是想要读取其他代码文件，以及做一些接口文件上传的处理

可以读取放到httprunner目录下面，然后在驱动代码界面这样引入
```python
from httprunner.builtin.time_helper import get_ts, get_day_fmt
from httprunner.builtin.auxiliary_func import img_value
```
<img width="715" alt="image" src="https://github.com/user-attachments/assets/8bb5d602-4533-4d3a-bfe5-99f6006d3c5b">

**Comment by tahitimoon** [comment]
> > 有问题直接在这里提就好啦
> 
> 还会有一个问题是：不同环境的登陆是怎么做的请求头Authorization环境配置 环境配置的流程是在用例接口运行的前置，我该如何调用登陆接口后，赋值token给环境配置里的请求头做环境变量呢？

- 建议先把https://lunar-link-docs.fun/文档详细看一遍，新建几个用例详细体验体验
- 不同环境只是请求地址不一样啦，多个不同配置的URL不同即可，不过如果是测试环境和正式环境，建议还是建了两个项目
- 配置里面写一些通用的就好啦（固定写死），token就写到每个接口的header中去引用就好
![image](https://github.com/user-attachments/assets/56aa84dd-50af-46af-90cf-5f2e8dcb849b)

**Comment by a851379672** [comment]
> > > 有问题直接在这里提就好啦
> > 
> > 
> > 还会有一个问题是：不同环境的登陆是怎么做的请求头Authorization环境配置 环境配置的流程是在用例接口运行的前置，我该如何调用登陆接口后，赋值token给环境配置里的请求头做环境变量呢？
> 
> * 建议先把[https://lunar-link-docs.fun/文档详细看一遍，新建几个用例详细体验体验](https://lunar-link-docs.fun/%E6%96%87%E6%A1%A3%E8%AF%A6%E7%BB%86%E7%9C%8B%E4%B8%80%E9%81%8D%EF%BC%8C%E6%96%B0%E5%BB%BA%E5%87%A0%E4%B8%AA%E7%94%A8%E4%BE%8B%E8%AF%A6%E7%BB%86%E4%BD%93%E9%AA%8C%E4%BD%93%E9%AA%8C)
> * 不同环境只是请求地址不一样啦，多个不同配置的URL不同即可，不过如果是测试环境和正式环境，建议还是多个项目区分
> * 配置里面写一些通用的就好啦（固定写死），token就写到每个接口的header中去引用就好



> > > 有问题直接在这里提就好啦
> > 
> > 
> > 还会有一个问题是：不同环境的登陆是怎么做的请求头Authorization环境配置 环境配置的流程是在用例接口运行的前置，我该如何调用登陆接口后，赋值token给环境配置里的请求头做环境变量呢？
> 
> * 建议先把[https://lunar-link-docs.fun/文档详细看一遍，新建几个用例详细体验体验](https://lunar-link-docs.fun/%E6%96%87%E6%A1%A3%E8%AF%A6%E7%BB%86%E7%9C%8B%E4%B8%80%E9%81%8D%EF%BC%8C%E6%96%B0%E5%BB%BA%E5%87%A0%E4%B8%AA%E7%94%A8%E4%BE%8B%E8%AF%A6%E7%BB%86%E4%BD%93%E9%AA%8C%E4%BD%93%E9%AA%8C)
> * 不同环境只是请求地址不一样啦，多个不同配置的URL不同即可，不过如果是测试环境和正式环境，建议还是多个项目区分
> * 配置里面写一些通用的就好啦（固定写死），token就写到每个接口的header中去引用就好
>   ![image](https://private-user-images.githubusercontent.com/37645552/390984397-56aa84dd-50af-46af-90cf-5f2e8dcb849b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjMzMDIsIm5iZiI6MTczMjg2MzAwMiwicGF0aCI6Ii8zNzY0NTU1Mi8zOTA5ODQzOTctNTZhYTg0ZGQtNTBhZi00NmFmLTkwY2YtNWYyZThkY2I4NDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA2NTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NWI0OGFhZTU2YTljYTZlYTA4NGE1YzA4MTAwNzg3OTY3YWIwMWI3MDk1NGYxNDczMTAzOTAwYjBjZjk0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CYcOLy92qkenHnY4XTf1ieSUEjNsFfWIRXfvRM-RdCQ)

这个回答跟我问的问题有点出入，一般自动化想要实现的这个效果，是类似在pytest的conftest里面做前置登陆获取token，然后其他接口直接引用
我想问的是平台能否做到前置登陆，然后把token复制给环境变量来做运行时的全局使用，而不是在每次运行的前置步骤还要加上登陆接口来做前置

**Comment by tahitimoon** [comment]
> > > > 有问题直接在这里提就好啦
> > > 
> > > 
> > > 还会有一个问题是：不同环境的登陆是怎么做的请求头Authorization环境配置 环境配置的流程是在用例接口运行的前置，我该如何调用登陆接口后，赋值token给环境配置里的请求头做环境变量呢？
> > 
> > 
> > 
> > * 建议先把[https://lunar-link-docs.fun/文档详细看一遍，新建几个用例详细体验体验](https://lunar-link-docs.fun/%E6%96%87%E6%A1%A3%E8%AF%A6%E7%BB%86%E7%9C%8B%E4%B8%80%E9%81%8D%EF%BC%8C%E6%96%B0%E5%BB%BA%E5%87%A0%E4%B8%AA%E7%94%A8%E4%BE%8B%E8%AF%A6%E7%BB%86%E4%BD%93%E9%AA%8C%E4%BD%93%E9%AA%8C)
> > * 不同环境只是请求地址不一样啦，多个不同配置的URL不同即可，不过如果是测试环境和正式环境，建议还是多个项目区分
> > * 配置里面写一些通用的就好啦（固定写死），token就写到每个接口的header中去引用就好
> 
> > > > 有问题直接在这里提就好啦
> > > 
> > > 
> > > 还会有一个问题是：不同环境的登陆是怎么做的请求头Authorization环境配置 环境配置的流程是在用例接口运行的前置，我该如何调用登陆接口后，赋值token给环境配置里的请求头做环境变量呢？
> > 
> > 
> > 
> > * 建议先把[https://lunar-link-docs.fun/文档详细看一遍，新建几个用例详细体验体验](https://lunar-link-docs.fun/%E6%96%87%E6%A1%A3%E8%AF%A6%E7%BB%86%E7%9C%8B%E4%B8%80%E9%81%8D%EF%BC%8C%E6%96%B0%E5%BB%BA%E5%87%A0%E4%B8%AA%E7%94%A8%E4%BE%8B%E8%AF%A6%E7%BB%86%E4%BD%93%E9%AA%8C%E4%BD%93%E9%AA%8C)
> > * 不同环境只是请求地址不一样啦，多个不同配置的URL不同即可，不过如果是测试环境和正式环境，建议还是多个项目区分
> > * 配置里面写一些通用的就好啦（固定写死），token就写到每个接口的header中去引用就好
> >   ![image](https://private-user-images.githubusercontent.com/37645552/390984397-56aa84dd-50af-46af-90cf-5f2e8dcb849b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjMzMDIsIm5iZiI6MTczMjg2MzAwMiwicGF0aCI6Ii8zNzY0NTU1Mi8zOTA5ODQzOTctNTZhYTg0ZGQtNTBhZi00NmFmLTkwY2YtNWYyZThkY2I4NDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA2NTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NWI0OGFhZTU2YTljYTZlYTA4NGE1YzA4MTAwNzg3OTY3YWIwMWI3MDk1NGYxNDczMTAzOTAwYjBjZjk0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CYcOLy92qkenHnY4XTf1ieSUEjNsFfWIRXfvRM-RdCQ)
> 
> 这个回答跟我问的问题有点出入，一般自动化想要实现的这个效果，是类似在pytest的conftest里面做前置登陆获取token，然后其他接口直接引用 我想问的是平台能否做到前置登陆，然后把token复制给环境变量来做运行时的全局使用，而不是在每次运行的前置步骤还要加上登陆接口来做前置（关于这个我尝试了一下在驱动代码实现，貌似可以用区分不同环境的登陆方法来做到赋值token给环境配置，比如test_login，pre_login这样，但是稍微有点呆）

可以按照自己的思路改造一下
