### ISSUE TITLE
docker部署容器内执行python3 manage.py migrate指令报错，mysql:8.0.21容器启动报错了

### ISSUE THREAD

**Issue by cfy3133** [tahitimoon/LunarLink#5]
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/d18bb2df-2835-4155-9986-2cf606db367f)
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/ce7d9989-260a-4dee-84df-e410a9cfc2dc)

**Comment by tahitimoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/43978367/318165684-d18bb2df-2835-4155-9986-2cf606db367f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDc1NDMsIm5iZiI6MTcxMTgwNzI0MywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgxNjU2ODQtZDE4YmIyZGYtMjgzNS00MTU1LTk5ODYtMmNmNjA2ZGIzNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE0MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NjZhYzk4MTM0M2E0YWY2Nzg5YWE0YTk3OWU1MzExZTQxNzExNGIwMmU2N2MwZmNjNGM0MWUwMWZmMjlkMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLe4l1GmR5_jonbFt8aCw4C9NERi69dc4zODj1JITJ4) ![image](https://private-user-images.githubusercontent.com/43978367/318165778-ce7d9989-260a-4dee-84df-e410a9cfc2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDc1NDMsIm5iZiI6MTcxMTgwNzI0MywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgxNjU3NzgtY2U3ZDk5ODktMjYwYS00ZGVlLTg0ZGYtZTQxMGE5Y2ZjMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE0MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmEwYjZiZTg2MGYwMmY3MzlmNWQ0OGVlY2E4NzdhM2NkOGM2MjRkZjg4Zjk2ZjU1NjNlYjI5Y2Q1NTA3YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KMiOHmNEOpTyZDVHYNX3fa22IWTswrkKB4K44ZkIuzE)

具体linux什么环境哈，可以如下描述：

操作步骤：
期望结果：
实际结果：
配置环境：

**Comment by cfy3133** [comment]
作者你好，
linux版本以及环境版本信息如下：
1）centos7版本为：CentOS Linux release 7.9.2009 (Core)
2）docker版本为：Docker version 26.0.0, build 2ae903e
3）docker-compose版本为：Docker Compose version v2.23.0

部署环境操作步骤：
1）git clone https://github.com/tahitimoon/LunarLink.git
2）cd LunarLink
3）mv .env.example .env
4）docker-compose up -d
5）docker exec -it lunar-link-django /bin/bash
6）python3 manage.py makemigrations

查看日志操作步骤：
1）docker ps -a
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/ee6dcc46-fea0-4af3-a970-36c1bc2a9eae)
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/9b9ad493-255a-41f2-be7d-6dd5b4670976)
2）日志报错信息如上截图所示，mysql容器未正常启动

如果作者还有疑问，请留言我一定配合

**Comment by cfy3133** [comment]
作者你好，解决了mysql容器启动问题如下：
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/75a31945-acbb-4aad-a459-88650fe539cc)
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/27c4f826-8a16-43c1-94d8-a34247c5a825)
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/1c41fffe-3c5a-40bf-97ed-7f292ec16295)

出现新问题如下：
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/a9a0bc20-6cf2-4e6b-91b9-447f3f4de1a1)

**Comment by tahitimoon** [comment]
> 作者你好，解决了mysql容器启动问题如下： ![image](https://private-user-images.githubusercontent.com/43978367/318234817-fe492ea8-2eb0-4680-97a0-50a4a72e284e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDk5MjcsIm5iZiI6MTcxMTg0OTYyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzQ4MTctZmU0OTJlYTgtMmViMC00NjgwLTk3YTAtNTBhNGE3MmUyODRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAxNDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTA2NTMxYWE4YTZiMGRlMTA0NWM2ZWU2MzE5ODgxYjlhMWRhOGIwYjdiOWM5ZTliZGExNDY4Njc0ZTYzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzSamooCnFxTrRNqniHoy2ylvoicKy6MMGtPuu00k_U) ![image](https://private-user-images.githubusercontent.com/43978367/318234577-27c4f826-8a16-43c1-94d8-a34247c5a825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDk5MjcsIm5iZiI6MTcxMTg0OTYyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzQ1NzctMjdjNGY4MjYtOGExNi00M2MxLTk0ZDgtYTM0MjQ3YzVhODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAxNDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyM2Y4NWQzZDQ1NDQxZWZjM2QwYTk2YmNhMTFkYWNjYThiM2NmN2NjMGYyMDI5ZjFlZWQyOWEzYTE4OTU5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EP9hDuh4hW2mbVS-DWfV0AAG5I3-ibsIoafEQFx3Eo) ![image](https://private-user-images.githubusercontent.com/43978367/318234597-1c41fffe-3c5a-40bf-97ed-7f292ec16295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDk5MjcsIm5iZiI6MTcxMTg0OTYyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzQ1OTctMWM0MWZmZmUtM2M1YS00MGJmLTk3ZWQtN2YyOTJlYzE2Mjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAxNDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3OGUxZGZlZGQ5NjZkZWI1MDVjZDk1OWJjZjBlZGJkZmQyYzVhODRhZDU3MzQyYTg3MGU0MzY4Y2RlNTAxOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vG9B8HNpgQiQ5QFY1P27eEYriVpOcvV6_b6WBzWx2kA)
> 
> 出现新问题如下： ![image](https://private-user-images.githubusercontent.com/43978367/318234711-a9a0bc20-6cf2-4e6b-91b9-447f3f4de1a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDk5MjcsIm5iZiI6MTcxMTg0OTYyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzQ3MTEtYTlhMGJjMjAtNmNmMi00ZTZiLTkxYjktNDQ3ZjNmNGRlMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAxNDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNTgwNTQ1YzJhMTY4MDcyMzdjZDQxOGYwNWRlNDQ1OTM3YTk1Y2FmOTk4YTIxZTQ4OWZmNGJiYzE4NzRhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ukpQ7OdPPADZtHHS2vnrz7pwNf4v4vcTB8wLSO8ISsI)

应该是`deployment/mysql/init/init.sql`脚本没生效，可以手动通过如下命令进入mysql容器设置：
```bash
#进入docker bash
sudo docker exec -it lunar-link-mysql bash
#进入mysql客户端命令
mysql -uroot -p
#输入密码 进入mysql客户端命令行
#切换到mysql数据库
use mysql;
#设置用户访问的ip
update user set Host='%' where User='root';
#刷新配置
flush privileges;
```
顺便问一下，在根目录执行`sudo docker compose up -d`命令时前面带`sudo`了吗？

**Comment by cfy3133** [comment]
作者你好，我是用root用户登录的，上面的我也执行了，好像还是报错，是报错其他的
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/c74005eb-f547-4858-a4fd-354d76c261a6)
然后再次执行：
 docker exec -it  lunar-link-mysql /bin/bash
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
FLUSH PRIVILEGES;

再次报错：
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/13faa50a-9437-40fe-8681-b70c49f7fe4f)

**Comment by tahitimoon** [comment]
> 作者你好，我是用root用户登录的，上面的我也执行了，好像还是报错，是报错其他的 ![image](https://private-user-images.githubusercontent.com/43978367/318236781-c74005eb-f547-4858-a4fd-354d76c261a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTE1MjcsIm5iZiI6MTcxMTg1MTIyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzY3ODEtYzc0MDA1ZWItZjU0Ny00ODU4LWE0ZmQtMzU0ZDc2YzI2MWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAyMTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDQ0NTlkMjZmNjQyMzAzZGE3YWNhMjRkNDM4ZjRkMDUyOTc0NjE1Yjk1MTJlNzBhOTI5MmUxMTM2MzM2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kz4LAYlqqK8qCwdgBA-91R8mNkUrxv8QReivC0xqznI) 然后再次执行： docker exec -it lunar-link-mysql /bin/bash mysql -uroot -proot USE mysql; ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root'; FLUSH PRIVILEGES;
> 
> 再次报错： ![image](https://private-user-images.githubusercontent.com/43978367/318236832-13faa50a-9437-40fe-8681-b70c49f7fe4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTE1MjcsIm5iZiI6MTcxMTg1MTIyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzY4MzItMTNmYWE1MGEtOTQzNy00MGZlLTg2ODEtYjcwYzQ5ZjdmZTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAyMTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOGQyMjI1OWEwN2I1NGYxYTdiN2MxYzAwNTZkYzcwMzNjNzc1YWE1MDYwZjQxZjM0NDc3YjczMzBjZmE5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1nCea1a-LaiuPxSsV_MU5oxt7Z2RLWUPHOslRNX8Wc8)

这么看数据库是可以连接上了，拿类似Navicat的工具手动创建一个lunarlink数据库试试，现在提示找不到数据库

**Comment by cfy3133** [comment]
作者你好，通过如下指令
docker exec -it lunar-link-mysql /bin/bash
mysql -uroot -proot
CREATE DATABASE lunarlink;
终于可以了，谢谢作者耐心回答，不过感觉docker-compose一键部署，mysql8.0以上还是很多坑呀，对应小白来说不是很友好，哈哈

**Comment by cfy3133** [comment]
作者你好，还有一个疑问：
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/d90bf332-ce61-4ea7-87b5-4ab594c07181)

**Comment by tahitimoon** [comment]
> 作者你好，还有一个疑问： ![image](https://private-user-images.githubusercontent.com/43978367/318237468-d90bf332-ce61-4ea7-87b5-4ab594c07181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTIzOTQsIm5iZiI6MTcxMTg1MjA5NCwicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzc0NjgtZDkwYmYzMzItY2U2MS00ZWE3LTg3YjUtNGFiNTk0YzA3MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAyMjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExODdmM2IyZjJiOTUwMDA3OTg5MjVhMjZjMWVhNzdhZjFkNDFiMjI0MGUzNjc1ODQ5NWNiMzU2NzU1Y2IyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JYIasGHErIprBQ-rdEhNMam0qAfTp_Jgq1xo-TS-PC0)

先进入后台设置改账号的姓名，为什么上面是灰色的，因为没有创建项目，详细的参照文档[https://lunar-link-docs.fun/](https://lunar-link-docs.fun/)
```bash
# 登录管理后台，设置账号姓名
http://localhost:8081/admin/

浏览器打开:
http://localhost:8081
用户/密码:管理员用户/密码
```

**Comment by cfy3133** [comment]
作者你好，我看下文档，谢谢，如下截图是否是个bug
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/6139646f-0bfa-47f4-91e0-0efbeabbb8ff)

**Comment by tahitimoon** [comment]
> 先进入后台设置改账号的姓名，为什么上面是灰色的，因为没有创建项目，详细的参照文档https://lunar-link-docs.fun/
> 
> ```shell
> # 登录管理后台，设置账号姓名
> http://localhost:8081/admin/
> 
> 浏览器打开:
> http://localhost:8081
> 用户/密码:管理员用户/密码
> ```

看看上面说的，先去django admin管理后台把admin账号的姓名设置好，不然姓名会显示null

**Comment by cfy3133** [comment]
好的，再次感谢耐心回复

**Comment by cfy3133** [comment]
作者你好，这里可优化下
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/037c6aaf-c50f-4348-a108-5031b592983c)

**Comment by tahitimoon** [comment]
> 作者你好，这里可优化下 ![image](https://private-user-images.githubusercontent.com/43978367/318238536-037c6aaf-c50f-4348-a108-5031b592983c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTQ2MDYsIm5iZiI6MTcxMTg1NDMwNiwicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzg1MzYtMDM3YzZhYWYtYzUwZi00MzQ4LWExMDgtNTAzMWI1OTI5ODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDAzMDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZGE1MWI1ZDUzYjc1OWY3YWVjOTRlMjg2YjRlNWY3M2JhMjUxOGEwNGFkOTg4ZWI3Nzk4M2U3YmQ1MjAwNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_CBDTTSOkG4ik2jZZ30dKKq5TjGifoaCCYdZw1rbpo)

现在小屏幕没做优化，在23、24寸屏幕上面显示应该是正常的

**Comment by cfy3133** [comment]
好的

**Comment by cfy3133** [comment]
作者你好，好像包括github这些网站没有办法录制，这种有办法解决嘛
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/6e718459-d941-484e-8dc8-8f0948919056)

**Comment by tahitimoon** [comment]
> 作者你好，好像包括github这些网站没有办法录制，这种有办法解决嘛 ![image](https://private-user-images.githubusercontent.com/43978367/318239990-6e718459-d941-484e-8dc8-8f0948919056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjU4MjcsIm5iZiI6MTcxMTg2NTUyNywicGF0aCI6Ii80Mzk3ODM2Ny8zMTgyMzk5OTAtNmU3MTg0NTktZDk0MS00ODRlLThkYzgtOGYwOTQ4OTE5MDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA2MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MjRlOTMyMzJjNzg0ZmFkM2FhNzAyZTAwMTczNmY3M2IxYTk4ZDZkNzE2ODg4YzdkYzlhNWY2NTU5MGZhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHS8N6DLKiq_asfa1FZ6glR58wyctI4n3kzk_KZ46Do)

试了一下百度，可以录制，一般用F12看看对应网站的接口地址是多少，别开其他代理
![image](https://github.com/tahitimoon/LunarLink/assets/37645552/75d0f8e0-a4cf-4ddc-9e68-893cb2657f40)

**Comment by cfy3133** [comment]
谢谢作者，我知道为啥了，有些浏览器会阻止掉，用国内的浏览器就可以了，再次感谢
![image](https://github.com/tahitimoon/LunarLink/assets/43978367/bdfc1da3-0381-422b-bd0b-1d20bb302f6a)
