### ISSUE TITLE
作者你好，为啥不支持post请求的录制

### ISSUE THREAD

**Issue by cfy3133** [tahitimoon/LunarLink#7]

**Comment by cfy3133** [comment]
好的，那就奇怪了，我录制登录接口以及其他有POST请求的接口，都没有抓取到，尴尬

**Comment by tahitimoon** [comment]
> 好的，那就奇怪了，我录制登录接口以及其他有POST请求的接口，都没有抓取到，尴尬

这个录制流量主要是根据接口地址筛选，F12看看具体的接口地址，有些网站域名地址并不是接口地址
